import { Schema, model, models } from "mongoose";

const storySchema = new Schema(
  {
    title: { type: String, required: true },
    genre: { type: String, required: true },
    premise: { type: String, required: true },
    tone: { type: String, required: true },
    enginePreset: { type: String, required: true, default: "freeform" },
    currentScene: { type: Schema.Types.Mixed, required: true },
    scenes: { type: [Schema.Types.Mixed], required: true, default: [] },
    summary: { type: String, required: true },
    summaryCandidate: { type: String, required: true, default: "" },
    worldRules: { type: [String], required: true, default: [] },
    memory: {
      shortTerm: { type: [Schema.Types.Mixed], required: true, default: [] },
      rollingSummaries: { type: [Schema.Types.Mixed], required: true, default: [] },
      canon: {
        type: Schema.Types.Mixed,
        required: true,
        default: {
          facts: [],
          irreversibleEvents: [],
          importantFlags: [],
          conflicts: [],
        },
      },
      entities: { type: [String], required: true, default: [] },
    },
    canonicalState: { type: Schema.Types.Mixed, required: true },
    availableActions: { type: [Schema.Types.Mixed], required: true, default: [] },
    turnHistory: { type: [Schema.Types.Mixed], required: true, default: [] },
    storyHistory: { type: [String], required: true, default: [] },
    coreState: {
      type: Schema.Types.Mixed,
      required: true,
      default: {
        genre: "custom",
        tone: "",
        currentArc: "Khởi đầu",
        turn: 0,
        gameOver: false,
        endingType: null,
        gameRules: [],
      },
    },
    dynamicStats: { type: Schema.Types.Mixed, required: true, default: {} },
    relationships: { type: Schema.Types.Mixed, required: true, default: {} },
    playerStats: {
      type: Schema.Types.Mixed,
      required: true,
      default: {
        health: 65,
        stamina: 60,
        morale: 55,
        trust: 40,
        suspicion: 20,
        danger: 15,
        stress: 25,
        focus: 55,
      },
    },
    inventory: { type: [Schema.Types.Mixed], required: true, default: [] },
    abilities: { type: [Schema.Types.Mixed], required: true, default: [] },
    flags: { type: [String], required: true, default: [] },
    worldMemory: { type: [Schema.Types.Mixed], required: true, default: [] },
    lastChoice: { type: String, default: null },
    gameOver: { type: Boolean, required: true, default: false },
    metadata: {
      branchKey: { type: String, required: true },
      turnCount: { type: Number, required: true, default: 0 },
      status: {
        type: String,
        enum: ["active", "completed", "paused"],
        required: true,
        default: "active",
      },
      lastUpdatedAt: { type: String, required: true },
      deterministic: { type: Boolean, required: true, default: false },
      seed: { type: String, required: true },
      storyOutputLanguage: { type: String, enum: ["en", "vi"], default: "en" },
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

export const StoryModel = models.Story ?? model("Story", storySchema);
